### ISSUE TITLE
[QUESTION] -I can not run the program rightly!  !  !

### ISSUE THREAD

**Issue by username123wy** [opencaesar/ecore-adapter#5]
## Description
I got an exception when I use this tool. I want to know what happened.

## Additional Context
The parameter of the command is "-i E:/demo -w E:/owldemo/owl.oml -o E:/owldemo"
The exception information is:
Exception in thread "main" java.lang.IllegalArgumentException: Unhandled parameter types: [null]
        at io.opencaesar.ecore2oml.EcoreToOml.getIri(EcoreToOml.java:444)
        at io.opencaesar.ecore2oml.EcoreToOml._getIri(EcoreToOml.java:281)
        at io.opencaesar.ecore2oml.EcoreToOml.getIri(EcoreToOml.java:437)
        at io.opencaesar.ecore2oml.EcoreToOml._addToVocabulary(EcoreToOml.java:219)
        at io.opencaesar.ecore2oml.EcoreToOml.addToVocabulary(EcoreToOml.java:416)
        at io.opencaesar.ecore2oml.EcoreToOml.run(EcoreToOml.java:88)
        at io.opencaesar.ecore2oml.App.run(App.java:145)
        at io.opencaesar.ecore2oml.App.main(App.java:98)

## Relevant screenshots
![image](https://user-images.githubusercontent.com/35055195/71447223-f2179280-2766-11ea-9a04-b7e6a564d445.png)

**Comment by melaasar** [comment]
It looks like your Ecore file has some unsupported syntax. Is it possible to attach it here (or a subset of it) so I can debug this?

**Comment by username123wy** [comment]
I have sloved this problem, Thanks. However, I'm having problems with the file import section. The screenshots below are the error message and the catalog file respectively. All my attempts have failed. I don't know how to solve it. I suspect it's the contents of the catalog file.
<img width="779" alt="Snipaste_2021-06-21_20-25-34" src="https://user-images.githubusercontent.com/35055195/122761540-f0347e00-d2ce-11eb-9e3a-c9c0bb42b7f5.png">
<img width="494" alt="Snipaste_2021-06-21_20-26-37" src="https://user-images.githubusercontent.com/35055195/122761611-03474e00-d2cf-11eb-9176-940103f291ee.png">
<img width="482" alt="Snipaste_2021-06-21_20-27-02" src="https://user-images.githubusercontent.com/35055195/122761657-0fcba680-d2cf-11eb-88d9-f25f91c41908.png">

**Comment by melaasar** [comment]
I think your catalog entries are very narrow. Please use a wider mapping like with:
https://github.com/opencaesar/eclipse-vocabularies/blob/master/catalog.xml

Also, you did not specify what dependencies you declared in your project. In order to be able to resolve rdf-schema, you need to have the core-vocabularies mappable from the catalog. One way to ensure that is to declare a dependency on core-vocabularies from your gradle script. For example: https://github.com/opencaesar/eclipse-vocabularies/blob/70ba689a9037b4b8ff16fa0ff7e3f062bf00ada5/build.gradle#L29, and then have a task that download those dependencies to a folder (e.g., build/oml) that is mapped from the catalog.xml. For example: https://github.com/opencaesar/eclipse-vocabularies/blob/master/eclipse-uml2/build.gradle#L12-L15.

I think you can follow the organization of the https://github.com/opencaesar/eclipse-vocabularies/eclipse-uml2 as an example. You do not have to use gradle subprojects though. You can merge its gradle.build with that of the root project.
